services:
  next:
    build:
      context: .
      target: next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    volumes:
      - .:/app