services:
  next:
    image: ghcr.io/alexispe/cda242-next/next:main
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.next-prod.rule=Host(`ec2-13-38-214-84.eu-west-3.compute.amazonaws.com`)"
      - "traefik.http.routers.next-prod.entrypoints=web"
    networks:
      - web

networks:
  web:
    name: web
    external: true